id: IDD0AEA74
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T15:22:46+00:00'
last_modified: '2022-06-08T05:32:40.530275+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG1657
  title: གསུང་འབུམ། དྷརྨ་བྷ་དྲ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    63A4:
      image_group_id: I1KG1739
      title: ''
      total_pages: 748
      order: 1
      base_file: 63A4.txt
    56E1:
      image_group_id: I1KG1740
      title: ''
      total_pages: 833
      order: 2
      base_file: 56E1.txt
    '4453':
      image_group_id: I1KG1741
      title: ''
      total_pages: 803
      order: 3
      base_file: 4453.txt
    E668:
      image_group_id: I1KG1742
      title: ''
      total_pages: 712
      order: 4
      base_file: E668.txt
    F7FF:
      image_group_id: I1KG1743
      title: ''
      total_pages: 640
      order: 5
      base_file: F7FF.txt
    '4780':
      image_group_id: I1KG1744
      title: ''
      total_pages: 930
      order: 6
      base_file: 4780.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
