id: IDD0AEA74
legacy_id: P006600
ocr_import_info:
  bdrc_scan_id: W1KG1657
  source: bdrc
  ocr_info:
    timestamp: '2020-03-21T15:15:36'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T08:39:10.465450+00:00'
last_modified: 2022-08-31 16:41:26.430836
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG1657
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG1657
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དྷརྨ་བྷ་དྲ།
  author: དངུལ་ཆུ་དྷརྨ་བྷ་དྲ།
statistics:
  ocr_word_mean_confidence_index: 0.6331972980913441
  ocr_word_median_confidence_index: 0.6600000262260437
quality: null
bases:
  I1KG1739:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1739
      total_pages: 748
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG1739.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6766754510499172
    legacy_id: v001
  I1KG1743:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1743
      total_pages: 640
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG1743.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6145394270594431
    legacy_id: v005
  I1KG1744:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1744
      total_pages: 930
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG1744.txt
    statistics:
      ocr_word_median_confidence_index: 0.6200000047683716
      ocr_word_mean_confidence_index: 0.6060884958327948
    legacy_id: v006
  I1KG1742:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1742
      total_pages: 712
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG1742.txt
    statistics:
      ocr_word_median_confidence_index: 0.7200000286102295
      ocr_word_mean_confidence_index: 0.6768209934128356
    legacy_id: v004
  I1KG1740:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1740
      total_pages: 833
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG1740.txt
    statistics:
      ocr_word_median_confidence_index: 0.5699999928474426
      ocr_word_mean_confidence_index: 0.5734438682702016
    legacy_id: v002
  I1KG1741:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG1741
      total_pages: 803
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG1741.txt
    statistics:
      ocr_word_median_confidence_index: 0.6899999976158142
      ocr_word_mean_confidence_index: 0.6497863177779706
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
